### ISSUE TITLE
Low resolution  of cropped image

### ISSUE THREAD

**Issue by davemg3** [hoangphuc3117/cropreceiptdemo#4]
Hi,
Nice code
But do you know why the image is alterated with your library (low quality compared to camera resolution)
I am trying to fix it but didnt see yet
Rgds

**Comment by davemg3** [comment]
Found it: 
to change these lines : 
```
 val options = BitmapFactory.Options()
            options.inSampleSize = **1**
```

**Comment by hoangphuc3117** [comment]
Hi davemg3, 

Thank you for your comment. Because this app is demo app for auto detecting corners of receipt, I reduced resolution of image to handle it more quickly

**Comment by davemg3** [comment]
the autodetection of corner is almost as good as CamCard. Wondering if a change on contrast or using bicolor black and white will not improve the autodetection.
Clean code anyway.
